name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: mskelton/setup-pnpm@v2
      - name: Build
        run: |
          for filename in slides/*.md; do
            dir=$(basename ${filename%.*})
            pnpm slidev build $filename --out dist/$dir --base /frontend-101/$dir
          done
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: slides/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
