name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: mskelton/setup-bun@v1
      - name: Build
        run: bun slidev build slides/*.md --base /frontend-101/
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: slides/dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
